org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
#org.gradle.offline=true

# Disable Gradle daemon
org.gradle.daemon=false

# Disable Kotlin daemon
kotlin.compiler.execution.strategy=in-process

# Reduce worker parallelism
org.gradle.workers.max=1

# Optional stability flags
kotlin.incremental=false