org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
#org.gradle.offline=true

# Disable Gradle daemon
#org.gradle.daemon=false

# Reduce worker parallelism
#org.gradle.workers.max=1

# Disable Kotlin daemon
#kotlin.compiler.execution.strategy=in-process
# Optional stability flags
#kotlin.incremental=false

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=59600
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=59600

#systemProp.socksProxyHost=127.0.0.1
#systemProp.socksProxyPort=59599
